version: '2'

services:
    wordpress:
        build: ./wordpress
        ports:
            - "80:80"
        depends_on:
            - db
        links:
            - db:mysql-server
    db:
        build: ./db
        expose:
            - 3306


